import type { TournamentStructure } from '../types';

export const TEAMS_25: TournamentStructure = {
  teamCount: 25,
  seedMap: [1, 11, 21, 31, 41, 51, 61, 71, 73, 63, 53, 43, 33, 23, 13, 4, 2, 12, 22, 32, 42, 52, 62, 72, 3],
  groups: [
    { letter: 'A', teamSlots: [1, 2, 3, 4] },
    { letter: 'B', teamSlots: [21, 22, 23] },
    { letter: 'C', teamSlots: [41, 42, 43] },
    { letter: 'D', teamSlots: [61, 62, 63] },
    { letter: 'E', teamSlots: [11, 12, 13] },
    { letter: 'F', teamSlots: [31, 32, 33] },
    { letter: 'G', teamSlots: [51, 52, 53] },
    { letter: 'H', teamSlots: [71, 72, 73] },
  ],
  roundOneRaces: [
    { raceNum: 1, homeSlot: 1, awaySlot: 2 },
    { raceNum: 2, homeSlot: 3, awaySlot: 4 },
    { raceNum: 3, homeSlot: 11, awaySlot: 12 },
    { raceNum: 4, homeSlot: 21, awaySlot: 22 },
    { raceNum: 5, homeSlot: 31, awaySlot: 32 },
    { raceNum: 6, homeSlot: 41, awaySlot: 42 },
    { raceNum: 7, homeSlot: 51, awaySlot: 52 },
    { raceNum: 8, homeSlot: 61, awaySlot: 62 },
    { raceNum: 9, homeSlot: 71, awaySlot: 72 },
    { raceNum: 10, homeSlot: 2, awaySlot: 3 },
    { raceNum: 11, homeSlot: 4, awaySlot: 1 },
    { raceNum: 12, homeSlot: 12, awaySlot: 13 },
    { raceNum: 13, homeSlot: 22, awaySlot: 23 },
    { raceNum: 14, homeSlot: 32, awaySlot: 33 },
    { raceNum: 15, homeSlot: 42, awaySlot: 43 },
    { raceNum: 16, homeSlot: 52, awaySlot: 53 },
    { raceNum: 17, homeSlot: 62, awaySlot: 63 },
    { raceNum: 18, homeSlot: 72, awaySlot: 73 },
    { raceNum: 19, homeSlot: 1, awaySlot: 3 },
    { raceNum: 20, homeSlot: 2, awaySlot: 4 },
    { raceNum: 21, homeSlot: 13, awaySlot: 11 },
    { raceNum: 22, homeSlot: 23, awaySlot: 21 },
    { raceNum: 23, homeSlot: 33, awaySlot: 31 },
    { raceNum: 24, homeSlot: 43, awaySlot: 41 },
    { raceNum: 25, homeSlot: 53, awaySlot: 51 },
    { raceNum: 26, homeSlot: 63, awaySlot: 61 },
    { raceNum: 27, homeSlot: 73, awaySlot: 71 },
  ],
  roundTwoGroups: [
    {
      groupNum: 'I',
      seedingEntries: [
        { positionCode: '', letter: 'A', label: 'Winner A' },
        { positionCode: '', letter: 'B', label: 'Winner B' },
        { positionCode: '', letter: 'C', label: 'Winner C' },
        { positionCode: '', letter: 'D', label: 'Winner D' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'A', awayLetter: 'B' },
        { raceNum: 2, homeLetter: 'C', awayLetter: 'D' },
        { raceNum: 3, homeLetter: 'B', awayLetter: 'C' },
        { raceNum: 4, homeLetter: 'D', awayLetter: 'A' },
        { raceNum: 5, homeLetter: 'A', awayLetter: 'C' },
        { raceNum: 6, homeLetter: 'B', awayLetter: 'D' },

      ],
    },
    {
      groupNum: 'II',
      seedingEntries: [
        { positionCode: '', letter: 'E', label: 'Winner E' },
        { positionCode: '', letter: 'F', label: 'Winner F' },
        { positionCode: '', letter: 'G', label: 'Winner G' },
        { positionCode: '', letter: 'H', label: 'Winner H' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'E', awayLetter: 'F' },
        { raceNum: 2, homeLetter: 'G', awayLetter: 'H' },
        { raceNum: 3, homeLetter: 'F', awayLetter: 'G' },
        { raceNum: 4, homeLetter: 'H', awayLetter: 'E' },
        { raceNum: 5, homeLetter: 'E', awayLetter: 'G' },
        { raceNum: 6, homeLetter: 'F', awayLetter: 'H' },

      ],
    },
    {
      groupNum: 'III',
      seedingEntries: [
        { positionCode: '', letter: 'I', label: '2nd A' },
        { positionCode: '', letter: 'J', label: '2nd B' },
        { positionCode: '', letter: 'K', label: '2nd C' },
        { positionCode: '', letter: 'L', label: '2nd D' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'I', awayLetter: 'J' },
        { raceNum: 2, homeLetter: 'K', awayLetter: 'L' },
        { raceNum: 3, homeLetter: 'J', awayLetter: 'K' },
        { raceNum: 4, homeLetter: 'L', awayLetter: 'I' },
        { raceNum: 5, homeLetter: 'I', awayLetter: 'K' },
        { raceNum: 6, homeLetter: 'J', awayLetter: 'L' },

      ],
    },
    {
      groupNum: 'IV',
      seedingEntries: [
        { positionCode: '', letter: 'M', label: '2nd E' },
        { positionCode: '', letter: 'N', label: '2nd F' },
        { positionCode: '', letter: 'O', label: '2nd G' },
        { positionCode: '', letter: 'P', label: '2nd H' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'M', awayLetter: 'N' },
        { raceNum: 2, homeLetter: 'O', awayLetter: 'P' },
        { raceNum: 3, homeLetter: 'N', awayLetter: 'O' },
        { raceNum: 4, homeLetter: 'P', awayLetter: 'M' },
        { raceNum: 5, homeLetter: 'M', awayLetter: 'O' },
        { raceNum: 6, homeLetter: 'N', awayLetter: 'P' },

      ],
    },
    {
      groupNum: 'V',
      seedingEntries: [
        { positionCode: '', letter: 'Q', label: '3rd  A' },
        { positionCode: '', letter: 'R', label: '3rd  B' },
        { positionCode: '', letter: 'S', label: '3rd  C' },
        { positionCode: '', letter: 'T', label: '3rd  D' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'Q', awayLetter: 'R' },
        { raceNum: 2, homeLetter: 'S', awayLetter: 'T' },
        { raceNum: 3, homeLetter: 'R', awayLetter: 'S' },
        { raceNum: 4, homeLetter: 'T', awayLetter: 'Q' },
        { raceNum: 5, homeLetter: 'Q', awayLetter: 'S' },
        { raceNum: 6, homeLetter: 'R', awayLetter: 'T' },

      ],
    },
    {
      groupNum: 'VI',
      seedingEntries: [
        { positionCode: '', letter: 'U', label: '3rd E' },
        { positionCode: '', letter: 'V', label: '3rd F' },
        { positionCode: '', letter: 'W', label: '3rd G' },
        { positionCode: '', letter: 'X', label: '3rd H' },
        { positionCode: '', letter: 'Y', label: '4th A' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'X', awayLetter: 'U' },
        { raceNum: 2, homeLetter: 'Y', awayLetter: 'W' },
        { raceNum: 3, homeLetter: 'U', awayLetter: 'V' },
        { raceNum: 4, homeLetter: 'W', awayLetter: 'X' },
        { raceNum: 5, homeLetter: 'W', awayLetter: 'U' },
        { raceNum: 6, homeLetter: 'Y', awayLetter: 'V' },
        { raceNum: 7, homeLetter: 'U', awayLetter: 'Y' },
        { raceNum: 8, homeLetter: 'V', awayLetter: 'X' },
        { raceNum: 9, homeLetter: 'V', awayLetter: 'W' },
        { raceNum: 10, homeLetter: 'X', awayLetter: 'Y' },

      ],
    },
  ],
  finals: [
    { label: '29th/30th', homeRef: 'Loser Group V', awayRef: 'Loser Group VI' },
    { label: '27th/28th', homeRef: 'Loser Group V', awayRef: 'Loser Group VI' },
    { label: '25th/26th', homeRef: 'Third Group V', awayRef: 'Third Group VI' },
    { label: '23rd/24th', homeRef: 'Third Group V', awayRef: 'Third Group VI' },
    { label: '21st/22nd', homeRef: 'Second Group V', awayRef: 'Second Group VI' },
    { label: '19th/20th', homeRef: 'Second Group V', awayRef: 'Second Group VI' },
    { label: '17th/18th', homeRef: 'Winner Group V', awayRef: 'Winner Group VI' },
    { label: '15th/16th', homeRef: 'Loser Group III', awayRef: 'Loser Group IV' },
    { label: '13th/14th', homeRef: 'Third Group III', awayRef: 'Third Group IV' },
    { label: '11th/12th', homeRef: 'Second Group III', awayRef: 'Second Group IV' },
    { label: '9th/10th', homeRef: 'Winner Group III', awayRef: 'Winner Group IV' },
    { label: '7th/8th', homeRef: 'Loser Group I', awayRef: 'Loser Group II' },
    { label: '5th/6th', homeRef: 'Third Group I', awayRef: 'Third Group II' },
    { label: '3rd/4th', homeRef: 'Second Group I', awayRef: 'Second Group II' },
    { label: '1st/2nd', homeRef: 'Winner Group I', awayRef: 'Winner Group II' },
  ],
  roundOneRaceCount: 27,
  roundTwoRaceCount: 46,
};
