import type { TournamentStructure } from '../types';

export const TEAMS_32: TournamentStructure = {
  teamCount: 32,
  groups: [
    { letter: 'A', teamSlots: [1, 2, 3, 4] },
    { letter: 'B', teamSlots: [21, 22, 23, 24] },
    { letter: 'C', teamSlots: [41, 42, 43, 44] },
    { letter: 'D', teamSlots: [61, 62, 63, 64] },
    { letter: 'E', teamSlots: [11, 12, 13, 14] },
    { letter: 'F', teamSlots: [31, 32, 33, 34] },
    { letter: 'G', teamSlots: [51, 52, 53, 54] },
    { letter: 'H', teamSlots: [71, 72, 73, 74] },
  ],
  roundOneRaces: [
    { raceNum: 1, homeSlot: 1, awaySlot: 2 },
    { raceNum: 2, homeSlot: 3, awaySlot: 4 },
    { raceNum: 3, homeSlot: 11, awaySlot: 12 },
    { raceNum: 4, homeSlot: 13, awaySlot: 14 },
    { raceNum: 5, homeSlot: 21, awaySlot: 22 },
    { raceNum: 6, homeSlot: 23, awaySlot: 24 },
    { raceNum: 7, homeSlot: 31, awaySlot: 32 },
    { raceNum: 8, homeSlot: 33, awaySlot: 34 },
    { raceNum: 9, homeSlot: 41, awaySlot: 42 },
    { raceNum: 10, homeSlot: 43, awaySlot: 44 },
    { raceNum: 11, homeSlot: 51, awaySlot: 52 },
    { raceNum: 12, homeSlot: 53, awaySlot: 54 },
    { raceNum: 13, homeSlot: 61, awaySlot: 62 },
    { raceNum: 14, homeSlot: 63, awaySlot: 64 },
    { raceNum: 15, homeSlot: 71, awaySlot: 72 },
    { raceNum: 16, homeSlot: 73, awaySlot: 74 },
    { raceNum: 17, homeSlot: 2, awaySlot: 3 },
    { raceNum: 18, homeSlot: 4, awaySlot: 1 },
    { raceNum: 19, homeSlot: 12, awaySlot: 13 },
    { raceNum: 20, homeSlot: 14, awaySlot: 11 },
    { raceNum: 21, homeSlot: 22, awaySlot: 23 },
    { raceNum: 22, homeSlot: 24, awaySlot: 21 },
    { raceNum: 23, homeSlot: 32, awaySlot: 33 },
    { raceNum: 24, homeSlot: 34, awaySlot: 31 },
    { raceNum: 25, homeSlot: 42, awaySlot: 43 },
    { raceNum: 26, homeSlot: 44, awaySlot: 41 },
    { raceNum: 27, homeSlot: 52, awaySlot: 53 },
    { raceNum: 28, homeSlot: 54, awaySlot: 51 },
    { raceNum: 29, homeSlot: 62, awaySlot: 63 },
    { raceNum: 30, homeSlot: 64, awaySlot: 61 },
    { raceNum: 31, homeSlot: 72, awaySlot: 73 },
    { raceNum: 32, homeSlot: 74, awaySlot: 71 },
    { raceNum: 33, homeSlot: 1, awaySlot: 3 },
    { raceNum: 34, homeSlot: 2, awaySlot: 4 },
    { raceNum: 35, homeSlot: 11, awaySlot: 13 },
    { raceNum: 36, homeSlot: 12, awaySlot: 14 },
    { raceNum: 37, homeSlot: 21, awaySlot: 23 },
    { raceNum: 38, homeSlot: 22, awaySlot: 24 },
    { raceNum: 39, homeSlot: 31, awaySlot: 33 },
    { raceNum: 40, homeSlot: 32, awaySlot: 34 },
    { raceNum: 41, homeSlot: 41, awaySlot: 43 },
    { raceNum: 42, homeSlot: 42, awaySlot: 44 },
    { raceNum: 43, homeSlot: 51, awaySlot: 53 },
    { raceNum: 44, homeSlot: 52, awaySlot: 54 },
    { raceNum: 45, homeSlot: 61, awaySlot: 63 },
    { raceNum: 46, homeSlot: 62, awaySlot: 64 },
    { raceNum: 47, homeSlot: 71, awaySlot: 73 },
    { raceNum: 48, homeSlot: 72, awaySlot: 74 },
  ],
  roundTwoGroups: [
    {
      groupNum: 'I',
      seedingEntries: [
        { positionCode: '', letter: 'A', label: 'Winner A' },
        { positionCode: '', letter: 'B', label: 'Winner B' },
        { positionCode: '', letter: 'C', label: 'Winner C' },
        { positionCode: '', letter: 'D', label: 'Winner D' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'A', awayLetter: 'B' },
        { raceNum: 2, homeLetter: 'C', awayLetter: 'D' },
        { raceNum: 3, homeLetter: 'B', awayLetter: 'C' },
        { raceNum: 4, homeLetter: 'D', awayLetter: 'A' },
        { raceNum: 5, homeLetter: 'A', awayLetter: 'C' },
        { raceNum: 6, homeLetter: 'B', awayLetter: 'D' },
      ],
    },
    {
      groupNum: 'II',
      seedingEntries: [
        { positionCode: '', letter: 'E', label: 'Winner E' },
        { positionCode: '', letter: 'F', label: 'Winner F' },
        { positionCode: '', letter: 'G', label: 'Winner G' },
        { positionCode: '', letter: 'H', label: 'Winner H' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'E', awayLetter: 'F' },
        { raceNum: 2, homeLetter: 'G', awayLetter: 'H' },
        { raceNum: 3, homeLetter: 'F', awayLetter: 'G' },
        { raceNum: 4, homeLetter: 'H', awayLetter: 'E' },
        { raceNum: 5, homeLetter: 'E', awayLetter: 'G' },
        { raceNum: 6, homeLetter: 'F', awayLetter: 'H' },
      ],
    },
    {
      groupNum: 'III',
      seedingEntries: [
        { positionCode: '', letter: 'I', label: '2nd A' },
        { positionCode: '', letter: 'J', label: '2nd B' },
        { positionCode: '', letter: 'K', label: '2nd C' },
        { positionCode: '', letter: 'L', label: '2nd D' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'I', awayLetter: 'J' },
        { raceNum: 2, homeLetter: 'K', awayLetter: 'L' },
        { raceNum: 3, homeLetter: 'J', awayLetter: 'K' },
        { raceNum: 4, homeLetter: 'L', awayLetter: 'I' },
        { raceNum: 5, homeLetter: 'I', awayLetter: 'K' },
        { raceNum: 6, homeLetter: 'J', awayLetter: 'L' },
      ],
    },
    {
      groupNum: 'IV',
      seedingEntries: [
        { positionCode: '', letter: 'M', label: '2nd E' },
        { positionCode: '', letter: 'N', label: '2nd F' },
        { positionCode: '', letter: 'O', label: '2nd G' },
        { positionCode: '', letter: 'P', label: '2nd H' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'M', awayLetter: 'N' },
        { raceNum: 2, homeLetter: 'O', awayLetter: 'P' },
        { raceNum: 3, homeLetter: 'N', awayLetter: 'O' },
        { raceNum: 4, homeLetter: 'P', awayLetter: 'M' },
        { raceNum: 5, homeLetter: 'M', awayLetter: 'O' },
        { raceNum: 6, homeLetter: 'N', awayLetter: 'P' },
      ],
    },
    {
      groupNum: 'V',
      seedingEntries: [
        { positionCode: '', letter: 'Q', label: '3rd A' },
        { positionCode: '', letter: 'R', label: '3rd B' },
        { positionCode: '', letter: 'S', label: '3rd C' },
        { positionCode: '', letter: 'T', label: '3rd D' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'Q', awayLetter: 'R' },
        { raceNum: 2, homeLetter: 'S', awayLetter: 'T' },
        { raceNum: 3, homeLetter: 'R', awayLetter: 'S' },
        { raceNum: 4, homeLetter: 'T', awayLetter: 'Q' },
        { raceNum: 5, homeLetter: 'Q', awayLetter: 'S' },
        { raceNum: 6, homeLetter: 'R', awayLetter: 'T' },
      ],
    },
    {
      groupNum: 'VI',
      seedingEntries: [
        { positionCode: '', letter: 'U', label: '3rd E' },
        { positionCode: '', letter: 'V', label: '3rd F' },
        { positionCode: '', letter: 'W', label: '3rd G' },
        { positionCode: '', letter: 'X', label: '3rd H' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'U', awayLetter: 'V' },
        { raceNum: 2, homeLetter: 'W', awayLetter: 'X' },
        { raceNum: 3, homeLetter: 'V', awayLetter: 'W' },
        { raceNum: 4, homeLetter: 'X', awayLetter: 'U' },
        { raceNum: 5, homeLetter: 'U', awayLetter: 'W' },
        { raceNum: 6, homeLetter: 'V', awayLetter: 'X' },
      ],
    },
    {
      groupNum: 'VII',
      seedingEntries: [
        { positionCode: '', letter: 'Y', label: 'Loser A' },
        { positionCode: '', letter: 'Z', label: 'Loser B' },
        { positionCode: '', letter: 'AA', label: 'Loser C' },
        { positionCode: '', letter: 'BB', label: 'Loser D' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'Y', awayLetter: 'Z' },
        { raceNum: 2, homeLetter: 'AA', awayLetter: 'BB' },
        { raceNum: 3, homeLetter: 'Z', awayLetter: 'AA' },
        { raceNum: 4, homeLetter: 'BB', awayLetter: 'Y' },
        { raceNum: 5, homeLetter: 'Y', awayLetter: 'AA' },
        { raceNum: 6, homeLetter: 'Z', awayLetter: 'BB' },
      ],
    },
    {
      groupNum: 'VIII',
      seedingEntries: [
        { positionCode: '', letter: 'CC', label: 'Loser E' },
        { positionCode: '', letter: 'DD', label: 'Loser F' },
        { positionCode: '', letter: 'EE', label: 'Loser G' },
        { positionCode: '', letter: 'FF', label: 'Loser H' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'CC', awayLetter: 'DD' },
        { raceNum: 2, homeLetter: 'EE', awayLetter: 'FF' },
        { raceNum: 3, homeLetter: 'DD', awayLetter: 'EE' },
        { raceNum: 4, homeLetter: 'FF', awayLetter: 'CC' },
        { raceNum: 5, homeLetter: 'CC', awayLetter: 'EE' },
        { raceNum: 6, homeLetter: 'DD', awayLetter: 'FF' },
      ],
    },
  ],
  finals: [
    { label: '31st/32nd', homeRef: 'Loser Group V', awayRef: 'Loser Group VI' },
    { label: '29th/30th', homeRef: 'Loser Group V', awayRef: 'Loser Group VI' },
    { label: '27th/28th', homeRef: 'Third Group V', awayRef: 'Third Group VI' },
    { label: '25th/26th', homeRef: 'Third Group V', awayRef: 'Third Group VI' },
    { label: '23rd/24th', homeRef: 'Second Group V', awayRef: 'Second Group VI' },
    { label: '21st/22nd', homeRef: 'Second Group V', awayRef: 'Second Group VI' },
    { label: '19th/20th', homeRef: 'Winner Group V', awayRef: 'Winner Group VI' },
    { label: '17th/18th', homeRef: 'Winner Group V', awayRef: 'Winner Group VI' },
    { label: '15th/16th', homeRef: 'Loser Group III', awayRef: 'Loser Group IV' },
    { label: '13th/14th', homeRef: 'Third Group III', awayRef: 'Third Group IV' },
    { label: '11th/12th', homeRef: 'Second Group III', awayRef: 'Second Group IV' },
    { label: '9th/10th', homeRef: 'Winner Group III', awayRef: 'Winner Group IV' },
    { label: '7th/8th', homeRef: 'Loser Group I', awayRef: 'Loser Group II' },
    { label: '5th/6th', homeRef: 'Third Group I', awayRef: 'Third Group II' },
    { label: '3rd/4th', homeRef: 'Second Group I', awayRef: 'Second Group II' },
    { label: '1st/2nd', homeRef: 'Winner Group I', awayRef: 'Winner Group II' },
  ],
  roundOneRaceCount: 48,
  roundTwoRaceCount: 48,
};
