import type { TournamentStructure } from '../types';

export const TEAMS_21: TournamentStructure = {
  teamCount: 21,
  groups: [
    { letter: 'A', teamSlots: [1, 2, 3] },
    { letter: 'B', teamSlots: [21, 22, 23] },
    { letter: 'C', teamSlots: [41, 42, 43] },
    { letter: 'D', teamSlots: [61, 62, 63] },
    { letter: 'E', teamSlots: [11, 12, 13] },
    { letter: 'F', teamSlots: [31, 32, 33] },
    { letter: 'G', teamSlots: [51, 52, 53] },
  ],
  roundOneRaces: [
    { raceNum: 1, homeSlot: 1, awaySlot: 2 },
    { raceNum: 2, homeSlot: 11, awaySlot: 12 },
    { raceNum: 3, homeSlot: 21, awaySlot: 22 },
    { raceNum: 4, homeSlot: 31, awaySlot: 32 },
    { raceNum: 5, homeSlot: 41, awaySlot: 42 },
    { raceNum: 6, homeSlot: 51, awaySlot: 52 },
    { raceNum: 7, homeSlot: 61, awaySlot: 62 },
    { raceNum: 8, homeSlot: 2, awaySlot: 3 },
    { raceNum: 9, homeSlot: 12, awaySlot: 13 },
    { raceNum: 10, homeSlot: 22, awaySlot: 23 },
    { raceNum: 11, homeSlot: 32, awaySlot: 33 },
    { raceNum: 12, homeSlot: 42, awaySlot: 43 },
    { raceNum: 13, homeSlot: 52, awaySlot: 53 },
    { raceNum: 14, homeSlot: 62, awaySlot: 63 },
    { raceNum: 15, homeSlot: 3, awaySlot: 1 },
    { raceNum: 16, homeSlot: 13, awaySlot: 11 },
    { raceNum: 17, homeSlot: 23, awaySlot: 21 },
    { raceNum: 18, homeSlot: 33, awaySlot: 31 },
    { raceNum: 19, homeSlot: 43, awaySlot: 41 },
    { raceNum: 20, homeSlot: 53, awaySlot: 51 },
    { raceNum: 21, homeSlot: 63, awaySlot: 61 },
  ],
  roundTwoGroups: [
    {
      groupNum: 'I',
      seedingEntries: [
        { positionCode: 'A1', letter: 'A', label: 'Winner A' },
        { positionCode: 'B1', letter: 'B', label: 'Winner B' },
        { positionCode: 'C1', letter: 'C', label: 'Winner C' },
        { positionCode: 'D1', letter: 'D', label: 'Winner D' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'A', awayLetter: 'B' },
        { raceNum: 2, homeLetter: 'C', awayLetter: 'D' },
        { raceNum: 3, homeLetter: 'B', awayLetter: 'C' },
        { raceNum: 4, homeLetter: 'D', awayLetter: 'A' },
        { raceNum: 5, homeLetter: 'A', awayLetter: 'C' },
        { raceNum: 6, homeLetter: 'B', awayLetter: 'D' },
      ],
    },
    {
      groupNum: 'II',
      seedingEntries: [
        { positionCode: 'E1', letter: 'E', label: 'Winner E' },
        { positionCode: 'F1', letter: 'F', label: 'Winner F' },
        { positionCode: 'G1', letter: 'G', label: 'Winner G' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'E', awayLetter: 'F' },
        { raceNum: 2, homeLetter: 'F', awayLetter: 'G' },
        { raceNum: 3, homeLetter: 'G', awayLetter: 'E' },
      ],
    },
    {
      groupNum: 'III',
      seedingEntries: [
        { positionCode: 'A2', letter: 'H', label: 'Runner Up A' },
        { positionCode: 'B2', letter: 'I', label: 'Runner Up B' },
        { positionCode: 'C2', letter: 'J', label: 'Runner Up C' },
        { positionCode: 'D2', letter: 'K', label: 'Runner Up D' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'H', awayLetter: 'I' },
        { raceNum: 2, homeLetter: 'J', awayLetter: 'K' },
        { raceNum: 3, homeLetter: 'I', awayLetter: 'J' },
        { raceNum: 4, homeLetter: 'H', awayLetter: 'J' },
        { raceNum: 5, homeLetter: 'I', awayLetter: 'K' },
      ],
    },
    {
      groupNum: 'IV',
      seedingEntries: [
        { positionCode: 'E2', letter: 'L', label: 'Runner Up E' },
        { positionCode: 'F2', letter: 'M', label: 'Runner Up F' },
        { positionCode: 'G2', letter: 'N', label: 'Runner Up G' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'L', awayLetter: 'M' },
        { raceNum: 2, homeLetter: 'M', awayLetter: 'N' },
        { raceNum: 3, homeLetter: 'N', awayLetter: 'L' },
      ],
    },
    {
      groupNum: 'V',
      seedingEntries: [
        { positionCode: 'A3', letter: 'O', label: 'Loser A' },
        { positionCode: 'B3', letter: 'P', label: 'Loser B' },
        { positionCode: 'C3', letter: 'Q', label: 'Loser C' },
        { positionCode: 'D3', letter: 'R', label: 'Loser D' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'O', awayLetter: 'P' },
        { raceNum: 2, homeLetter: 'Q', awayLetter: 'R' },
        { raceNum: 3, homeLetter: 'P', awayLetter: 'Q' },
        { raceNum: 4, homeLetter: 'R', awayLetter: 'O' },
        { raceNum: 5, homeLetter: 'O', awayLetter: 'Q' },
        { raceNum: 6, homeLetter: 'P', awayLetter: 'R' },
      ],
    },
    {
      groupNum: 'VI',
      seedingEntries: [
        { positionCode: 'E3', letter: 'S', label: 'Loser E' },
        { positionCode: 'F3', letter: 'T', label: 'Loser F' },
        { positionCode: 'G3', letter: 'U', label: 'Loser G' },
      ],
      races: [
        { raceNum: 1, homeLetter: 'S', awayLetter: 'T' },
        { raceNum: 2, homeLetter: 'T', awayLetter: 'U' },
        { raceNum: 3, homeLetter: 'U', awayLetter: 'S' },
      ],
    },
  ],
  finals: [
    { label: '19th/20th', homeRef: 'Third Group V', awayRef: 'Third Group VI' },
    { label: '17th/18th', homeRef: 'Second Group V', awayRef: 'Second Group VI' },
    { label: '15th/16th', homeRef: 'Winner Group V', awayRef: 'Winner Group VI' },
    { label: '12th/13th', homeRef: 'Third Group III', awayRef: 'Third Group IV' },
    { label: '10th/11th', homeRef: 'Second Group III', awayRef: 'Second Group IV' },
    { label: '8th/9th', homeRef: 'Winner Group III', awayRef: 'Winner Group IV' },
    { label: '5th/6th', homeRef: 'Third Group I', awayRef: 'Third Group II' },
    { label: '3rd/4th', homeRef: 'Second Group I', awayRef: 'Second Group II' },
    { label: '1st/2nd', homeRef: 'Winner Group I', awayRef: 'Winner Group II' },
  ],
  roundOneRaceCount: 21,
  roundTwoRaceCount: 27,
};
